# Example configuration file for project output and logging

[production]
remove = ["input_copc", "classified_copc", "rescaled_copc", "grid_shell_copc", "output_viewshed_copc_3d", "output_viewshed_copc_2d"]
logging_level = "INFO"

[testing]
remove = ["rescaled_copc"]
logging_level = "DEBUG"

# Users can add more profiles as needed
# [custom_profile]
# save_files = [ ... ]
# logging_level = "INFO"
